#!/bin/zsh

if [[ -z $(plenv version) ]]; then
    anyenv init
    plenv init
    plenv install 5.22.0
    plenv global 5.22.0
    plenv rehash
    plenv install-cpanm
fi

if [[ -z $(rbenv version) ]]; then
    anyenv init
    rbenv init
    rbenv install 2.3.0
    rbenv global 2.3.0
    rbenv rehash
fi

if [[ -z $(ndenv version) ]]; then
    anyenv init
    ndenv init
    ndenv install v5.6.0
    ndenv global v5.6.0
    nbenv rehash
fi
